// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQhgMcLz9fKnYJs3J7hw1B9jPlE4SobYk',
    appId: '1:200566966632:web:2bce6d08ad892bda2a2edd',
    messagingSenderId: '200566966632',
    projectId: 'mobileapp-final-f25bc',
    authDomain: 'mobileapp-final-f25bc.firebaseapp.com',
    storageBucket: 'mobileapp-final-f25bc.firebasestorage.app',
    measurementId: 'G-BGWL798Q87',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDus49Km2XoS91FefsQH6wqGRFJg5xp9YM',
    appId: '1:200566966632:android:e915b6be6fa5abbf2a2edd',
    messagingSenderId: '200566966632',
    projectId: 'mobileapp-final-f25bc',
    storageBucket: 'mobileapp-final-f25bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1KUABlkCiq8feEg4pfvyjLwqDSal9kNI',
    appId: '1:200566966632:ios:96cc3501a93a79302a2edd',
    messagingSenderId: '200566966632',
    projectId: 'mobileapp-final-f25bc',
    storageBucket: 'mobileapp-final-f25bc.firebasestorage.app',
    iosBundleId: 'com.example.mobileapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1KUABlkCiq8feEg4pfvyjLwqDSal9kNI',
    appId: '1:200566966632:ios:96cc3501a93a79302a2edd',
    messagingSenderId: '200566966632',
    projectId: 'mobileapp-final-f25bc',
    storageBucket: 'mobileapp-final-f25bc.firebasestorage.app',
    iosBundleId: 'com.example.mobileapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQhgMcLz9fKnYJs3J7hw1B9jPlE4SobYk',
    appId: '1:200566966632:web:2241e4e5fc58b1e22a2edd',
    messagingSenderId: '200566966632',
    projectId: 'mobileapp-final-f25bc',
    authDomain: 'mobileapp-final-f25bc.firebaseapp.com',
    storageBucket: 'mobileapp-final-f25bc.firebasestorage.app',
    measurementId: 'G-FTMV296C2H',
  );
}
